### ISSUE TITLE
Can't remove <select> element in IE

### ISSUE THREAD

**Issue by zhangxinxu** [chenzhenxi/element-remove#6]
demo: [https://www.zhangxinxu.com/study/201908/remove-ie.html](https://www.zhangxinxu.com/study/201908/remove-ie.html)

&lt;button&gt; and some other elements can be removed normally.

but it report 'Invalid Argument' error when I try to remove &lt;select&gt; element.

IE version: IE9/IE10/IE11.

**Comment by chenzhenxi** [comment]
Thank you for the demo. Will try it tonight.

**Comment by zhangxinxu** [comment]
I see, HTMLSelectElement has own remove method，which used for removing &lt;option&gt; element。 [https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/remove](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/remove) 

Chrome is very smart，if there are no parameters, remove the &lt;select&gt; element itself, and if there are parameters, remove &lt;option&gt; element.
